
package za.co.example.unitconverter.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import za.co.example.unitconverter.ObjectFactory;
import za.co.example.unitconverter.SupportedUnitsRequest;
import za.co.example.unitconverter.SupportedUnitsResponse;
import za.co.example.unitconverter.UnitConversionRequest;
import za.co.example.unitconverter.UnitConversionResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UnitConverter", targetNamespace = "http://example.co.za/unitconverter/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UnitConverter {


    /**
     * 
     * @param body
     * @return
     *     returns za.co.example.unitconverter.UnitConversionResponse
     * @throws UnsupportedUnit
     */
    @WebMethod
    @WebResult(name = "unitConversionResponse", targetNamespace = "http://example.co.za/unitconverter/", partName = "body")
    public UnitConversionResponse convert(
        @WebParam(name = "unitConversionRequest", targetNamespace = "http://example.co.za/unitconverter/", partName = "body")
        UnitConversionRequest body)
        throws UnsupportedUnit
    ;

    /**
     * 
     * @param body
     * @return
     *     returns za.co.example.unitconverter.SupportedUnitsResponse
     */
    @WebMethod
    @WebResult(name = "supportedUnitsResponse", targetNamespace = "http://example.co.za/unitconverter/", partName = "body")
    public SupportedUnitsResponse getSupportedUnits(
        @WebParam(name = "supportedUnitsRequest", targetNamespace = "http://example.co.za/unitconverter/", partName = "body")
        SupportedUnitsRequest body);

}
