
package za.co.solms.example.simple.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "unknownArtistOrSong", targetNamespace = "http://solms.co.za/example/simple")
public class UnknownArtistOrSong
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private za.co.solms.example.simple.UnknownArtistOrSong faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public UnknownArtistOrSong(String message, za.co.solms.example.simple.UnknownArtistOrSong faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public UnknownArtistOrSong(String message, za.co.solms.example.simple.UnknownArtistOrSong faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: za.co.solms.example.simple.UnknownArtistOrSong
     */
    public za.co.solms.example.simple.UnknownArtistOrSong getFaultInfo() {
        return faultInfo;
    }

}
